aa: rand-m7-mstd0.5-inc1
amp: true
apex_amp: false
aug_repeats: 0
aug_splits: 0
batch_size: 256
bce_loss: true
bias_decay: true
bn_eps: null
bn_momentum: null
channels_last: false
checkpoint_hist: 2
clip_grad: null
clip_mode: norm
color_jitter: 0.4
configure: job_101_adan2.yaml
cooldown_epochs: 10
crop_pct: 0.95
cutmix: 1.0
cutmix_minmax: null
data_dir: /dataset/imagenet
dataset: ''
decay_epochs: 100
decay_rate: 0.1
dist_bn: reduce
drop: 0.0
drop_block: null
drop_connect: null
drop_path: 0.1
epoch_repeats: 0.0
epochs: 100
eval_metric: top1
experiment: ''
gp: null
hflip: 0.5
img_size: null
initial_checkpoint: ''
input_size: null
interpolation: ''
jsd_loss: false
local_rank: 0
log_interval: 50
log_wandb: false
lr: 0.01
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_k_decay: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
max_grad_norm: 5.0
mean: null
min_lr: 0.0001
mixup: 0.1
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: resnet101
model_ema: false
model_ema_decay: 0.9998
model_ema_force_cpu: false
momentum: 0.9
native_amp: false
no_aug: false
no_prefetcher: false
no_prox: false
no_resume_opt: false
num_classes: null
opt: adan
opt_betas:
- 0.98
- 0.92
- 0.99
opt_eps: 1.0e-08
output: ./exp_results/res101-100-
patience_epochs: 10
pin_mem: false
pretrained: false
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.0
resplit: false
resume: model_best.pth.tar
save_images: false
scale:
- 0.08
- 1.0
sched: cosine
seed: 3407
smoothing: 0.0
split_bn: false
start_epoch: null
std: null
sync_bn: false
torchscript: false
train_interpolation: random
train_split: train
tta: 0
use_multi_epochs_loader: false
val_split: validation
validation_batch_size: null
vflip: 0.0
warmup_epochs: 40
warmup_lr: 1.0e-09
weight_decay: 0.02
workers: 8
