aa: rand-m7-mstd0.5-inc1
amp: true
apex_amp: false
aug_repeats: 0
aug_splits: 0
batch_size: 256
bce_loss: true
bias_decay: false
bn_eps: null
bn_momentum: null
bn_tf: false
channels_last: false
checkpoint_hist: 2
clip_grad: null
clip_mode: norm
color_jitter: 0.4
cooldown_epochs: 10
crop_pct: null
cutmix: 1.0
cutmix_minmax: null
data_dir: /dataset/common/imagenet-raw
dataset: ''
decay_epochs: 100
decay_rate: 0.1
dist_bn: reduce
drop: 0.0
drop_block: null
drop_connect: null
drop_path: 0.05
epoch_repeats: 0.0
epochs: 150
eval_metric: top1
experiment: ''
gp: null
hflip: 0.5
img_size: null
initial_checkpoint: ''
input_size: null
interpolation: ''
jsd_loss: false
local_rank: 0
log_interval: 50
log_wandb: false
lr: 0.015
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_k_decay: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
max_grad_norm: 0.0
mean: null
min_lr: 1.0e-08
mixup: 0.2
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: deit_small_patch16_224
model_ema: false
model_ema_decay: 0.9998
model_ema_force_cpu: false
momentum: 0.9
native_amp: false
no_aug: false
no_prefetcher: false
no_prox: false
no_resume_opt: false
num_classes: null
opt: adan
opt_betas:
- 0.98
- 0.92
- 0.99
opt_debug: 5
opt_eps: 1.0e-08
output: ./exp_results/deit-small-bs-test-
patience_epochs: 10
pin_mem: false
pretrained: false
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.0
resplit: false
resume: ''
save_images: false
scale:
- 0.08
- 1.0
sched: cosine
seed: 1005
smoothing: 0.1
split_bn: false
start_epoch: null
std: null
sync_bn: false
torchscript: false
train_interpolation: random
train_split: train
tta: 0
use_multi_epochs_loader: false
val_split: validation
validation_batch_size: null
vflip: 0.0
warmup_epochs: 60
warmup_lr: 1.0e-08
weight_decay: 0.02
workers: 10
